spring.application.name=first-pet-project-exchanger

spring.datasource.url=jdbc:postgresql://localhost:5433/javadb
spring.datasource.username=postgres
spring.datasource.password=mT*pH&mc+U

spring.threads.virtual.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true